framework:
    ide:    'xdebug://%%f:%%l'

    secret: '%env(APP_SECRET)%'

    csrf_protection:
        enabled: true
    validation:
        enable_annotations: true
    annotations:
        enabled: true

    #http_method_override: true

    session:
        handler_id: session.handler.native_file
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'

    php_errors:
        log: true

    templating:
        engines: ['twig']
