framework:
    default_locale: '%locale%'

    translator:
        paths:
            - '%kernel.project_dir%/config/translations'
        fallbacks:
            - '%locale%'

services:
    translation.loader.yaml:
        class: Symfony\Component\Translation\Loader\YamlFileLoader
        tags:
            - { name: translation.loader, alias: yaml }
